"""Stable, presentation-neutral API for asynchronous MySQL execution."""

from mysql_client.cancellation import CancellationToken
from mysql_client.configuration import MySqlConnectionConfig, SecretValue
from mysql_client.driver_adapter import (
    AiomysqlDriverFactory,
    DriverColumn,
    DriverConnection,
    DriverCursor,
    DriverFactory,
    QueryKiller,
)
from mysql_client.enums import (
    CancellationReason,
    Capability,
    ErrorCode,
    ExecutionPolicy,
    ExplainFormat,
    InputSource,
    PolicyViolationReason,
    SqlParseReason,
    SqlStatementType,
    TransactionAction,
)
from mysql_client.errors import (
    AuthenticationError,
    ClientError,
    ComparisonError,
    ConfigurationError,
    ConnectionError,
    DatabaseNotFoundError,
    ExecutionPolicyError,
    InternalError,
    InvalidArgumentError,
    QueryCancelledError,
    QueryExecutionError,
    QueryTimeoutError,
    SqlParseError,
    UnsupportedSqlError,
    error_report_from_exception,
)
from mysql_client.parser import MySqlSqlParser
from mysql_client.policy import ExecutionPolicyValidator, validate_execution_policy
from mysql_client.protocols import CancellationController, QuerySession, SqlParser
from mysql_client.request_models import (
    BenchmarkRequest,
    CompareRequest,
    ExecutionPolicyDefaults,
    ExplainRequest,
    ParsedSql,
    ReadRequest,
    Request,
    SqlInput,
    WriteRequest,
)
from mysql_client.result_models import (
    BenchmarkResult,
    ColumnDefinition,
    CompareResult,
    DatabaseRow,
    ErrorReport,
    ExecutionMetadata,
    ExplainResult,
    QueryResult,
    ResponsePayload,
    TargetMetadata,
    WriteResult,
)
from mysql_client.session import MySqlSession, SessionState
from mysql_client.value_models import (
    ByteCount,
    DatabaseScalar,
    DatabaseValue,
    JsonScalar,
    JsonValue,
    Milliseconds,
    ProfileName,
    RowCount,
    SqlText,
)

__all__ = [
    "AiomysqlDriverFactory",
    "AuthenticationError",
    "BenchmarkRequest",
    "BenchmarkResult",
    "ByteCount",
    "CancellationController",
    "CancellationReason",
    "CancellationToken",
    "Capability",
    "ClientError",
    "ColumnDefinition",
    "CompareRequest",
    "CompareResult",
    "ComparisonError",
    "ConfigurationError",
    "ConnectionError",
    "DatabaseNotFoundError",
    "DatabaseRow",
    "DatabaseScalar",
    "DatabaseValue",
    "DriverColumn",
    "DriverConnection",
    "DriverCursor",
    "DriverFactory",
    "ErrorCode",
    "ErrorReport",
    "ExecutionMetadata",
    "ExecutionPolicy",
    "ExecutionPolicyDefaults",
    "ExecutionPolicyError",
    "ExecutionPolicyValidator",
    "ExplainFormat",
    "ExplainRequest",
    "ExplainResult",
    "InputSource",
    "InternalError",
    "InvalidArgumentError",
    "JsonScalar",
    "JsonValue",
    "Milliseconds",
    "MySqlConnectionConfig",
    "MySqlSession",
    "MySqlSqlParser",
    "ParsedSql",
    "PolicyViolationReason",
    "ProfileName",
    "QueryCancelledError",
    "QueryExecutionError",
    "QueryKiller",
    "QueryResult",
    "QuerySession",
    "QueryTimeoutError",
    "ReadRequest",
    "Request",
    "ResponsePayload",
    "RowCount",
    "SecretValue",
    "SessionState",
    "SqlInput",
    "SqlParseError",
    "SqlParseReason",
    "SqlParser",
    "SqlStatementType",
    "SqlText",
    "TargetMetadata",
    "TransactionAction",
    "UnsupportedSqlError",
    "WriteRequest",
    "WriteResult",
    "error_report_from_exception",
    "validate_execution_policy",
]
