"""Compatibility imports for client request models."""

from mysql_client.domain.requests import (
    BenchmarkRequest,
    CompareRequest,
    ExecutionPolicyDefaults,
    ExplainRequest,
    InspectionRequest,
    ParsedSql,
    ReadRequest,
    Request,
    SchemaDatabasesRequest,
    SchemaDescribeRequest,
    SchemaIndexesRequest,
    SchemaStatsRequest,
    SchemaTablesRequest,
    ServerCapabilitiesRequest,
    ServerInspectRequest,
    SqlInput,
    WriteRequest,
)

__all__ = [
    "BenchmarkRequest",
    "CompareRequest",
    "ExecutionPolicyDefaults",
    "ExplainRequest",
    "InspectionRequest",
    "ParsedSql",
    "ReadRequest",
    "Request",
    "SchemaDatabasesRequest",
    "SchemaDescribeRequest",
    "SchemaIndexesRequest",
    "SchemaStatsRequest",
    "SchemaTablesRequest",
    "ServerCapabilitiesRequest",
    "ServerInspectRequest",
    "SqlInput",
    "WriteRequest",
]
